// Generated by openapi-typescript from the backend Swagger spec.
// Regenerate: npx openapi-typescript $VITE_API_URL/swagger/v1/swagger.json -o src/types/api.d.ts
// This is the placeholder — replace with the generated file once the backend is running.

export type PaginatedResult<T> = {
  items: T[]
  totalCount: number
  pageNumber: number
  pageSize: number
  totalPages: number
}

export type ResponseResult<T> = {
  success: boolean
  data?: T
  message?: string
  errors?: string[]
}

export type LoginRequest = {
  email: string
  password: string
}

export type AuthResponse = {
  token: string
  refreshToken: string
  user: {
    id: string
    email: string
    firstName: string
    lastName: string
    role: string
    tenantId: number
    tenantName?: string
  }
}

export type RefreshRequest = {
  refreshToken: string
}
